### ISSUE TITLE
missing MOODLE_INTERNAL

### ISSUE THREAD

**Issue by ak4t0sh** [adpe/moodle-local_pluginsfetcher#1]
`defined('MOODLE_INTERNAL') || die();` should be added in lang/en/local_pluginsfetcher.php

**Comment by adpe** [comment]
Hi @ak4t0sh 

It's not a must-have to include this line in the lang file, but anyway I put it in. The Moodle Code Checker (https://github.com/moodlehq/moodle-local_codechecker) doesn't expect this inclusion.

Thanks,
Adrian
