### ISSUE TITLE
check capability before processing

### ISSUE THREAD

**Issue by ak4t0sh** [adpe/moodle-local_pluginsfetcher#2]
Capability check should be put before main processing.

https://github.com/adpe/moodle-local_pluginsfetcher/blob/7635b6c6395552da6a63271a281e9d839a7a58d4/externallib.php#L88-L89
should be moved before 
https://github.com/adpe/moodle-local_pluginsfetcher/blob/7635b6c6395552da6a63271a281e9d839a7a58d4/externallib.php#L64

This will prevent useless processing (and potential DOS) for unauthorized users.

**Comment by adpe** [comment]
Wow, thanks @ak4t0sh you're right. I don't know how I missed it.

Thanks for your findings,
Adrian
